# @no-redirect
POST http://localhost:8080/adduser
Content-Type: application/json

{
  "firstName": "Udhayakumar",
  "lastName": "T",
  "email": "dev.udhayakumar",
  "password": "123456",
  "role" : "ROLE_USER"
}

###
POST http://localhost:8080/adduser
Content-Type: application/json

{
  "firstName": "Vaishnavi",
  "lastName": "S",
  "email": "vaishnaviselvi@gmail.com",
  "password": "123456",
  "role" : "ROLE_USER"
}